#!/usr/bin/env python3
"""
Quantum Chemistry Analysis Table Explorer

This script creates exploratory plots for the quantum chemistry analysis tables 
generated by the preprocessing pipeline. These plots help visualize the data 
before deciding on specific plot types for detailed analysis.
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pathlib import Path

# Import centralized color mappings from plots.py
try:
    from plots import (AXIAL_LIGAND_COLOR_MAP, CHARGE_MULTIPLICITY_COLOR_MAP, 
                      COLORBLIND_PALETTE, EXTENDED_COLORBLIND_PALETTE,
                      get_axial_ligand_colors, get_charge_multiplicity_colors)
except ImportError:
    # Fallback if plots.py is not available
    AXIAL_LIGAND_COLOR_MAP = {
        'CYS-HOH': '#9467bd',  # Purple
        'HIS-HIS': '#0072B2',  # Blue
        'HIS-HOH': '#009E73',  # Green
        'HIS-MET': '#D55E00',  # Red
        'HIS-OXY': '#F0E442'   # Yellow
    }
    CHARGE_MULTIPLICITY_COLOR_MAP = {
        '0,1': '#0072B2', '0_1': '#0072B2', '0-1': '#0072B2',
        '0,2': '#009E73', '0_2': '#009E73', '0-2': '#009E73',
        '0,3': '#D55E00', '0_3': '#D55E00', '0-3': '#D55E00',
        '0,5': '#009E73', '0_5': '#009E73', '0-5': '#009E73',
        '1,2': '#D55E00', '1_2': '#D55E00', '1-2': '#D55E00',
        '1,5': '#56B4E9', '1_5': '#56B4E9', '1-5': '#56B4E9',
        '1,6': '#595959', '1_6': '#595959', '1-6': '#595959',
        '-1,2': '#2ca02c', '-1_2': '#2ca02c', '-1-2': '#2ca02c',
        '-1,4': '#d62728', '-1_4': '#d62728', '-1-4': '#d62728',
        '-1,6': '#9467bd', '-1_6': '#9467bd', '-1-6': '#9467bd'
    }
    COLORBLIND_PALETTE = ['#0072B2', '#009E73', '#D55E00', '#CC79A7', '#F0E442', '#56B4E9', '#E69F00']
    
    def get_axial_ligand_colors(combinations, extended=False):
        color_map = {}
        for i, combo in enumerate(combinations):
            if combo in AXIAL_LIGAND_COLOR_MAP:
                color_map[combo] = AXIAL_LIGAND_COLOR_MAP[combo]
            else:
                color_map[combo] = COLORBLIND_PALETTE[i % len(COLORBLIND_PALETTE)]
        return color_map
    
    def get_charge_multiplicity_colors(combinations, extended=False):
        color_map = {}
        for i, combo in enumerate(combinations):
            if combo in CHARGE_MULTIPLICITY_COLOR_MAP:
                color_map[combo] = CHARGE_MULTIPLICITY_COLOR_MAP[combo]
            else:
                color_map[combo] = COLORBLIND_PALETTE[i % len(COLORBLIND_PALETTE)]
        return color_map

class QMAnalysisPlotter:
    def __init__(self, table_dir="/home/pbuser/Desktop/PhD_WORK/heme/prior_analysis/qm_analysis_tables/"):
        """Initialize the plotter with the directory containing analysis tables."""
        self.table_dir = Path(table_dir)
        self.output_dir = self.table_dir / "exploratory_plots"
        self.output_dir.mkdir(exist_ok=True)
        
        # Load all available tables
        self.tables = {}
        self.auxiliary_data = {}
        self.load_tables()
        self.load_auxiliary_data()
        
        # Set plotting style
        plt.style.use('default')
        sns.set_palette("husl")
        
        # Outlier reports
        self.outlier_reports = {}
        
        # Use centralized color mappings
        self.axial_color_map = AXIAL_LIGAND_COLOR_MAP
        self.charge_mult_color_map = CHARGE_MULTIPLICITY_COLOR_MAP
        
    def load_tables(self):
        """Load all CSV files in the table directory."""
        csv_files = list(self.table_dir.glob("*.csv"))
        
        for csv_file in csv_files:
            table_name = csv_file.stem
            try:
                df = pd.read_csv(csv_file)
                self.tables[table_name] = df
                print(f"Loaded {table_name}: {len(df)} rows, {len(df.columns)} columns")
            except Exception as e:
                print(f"Error loading {csv_file}: {e}")
                
    def load_auxiliary_data(self):
        """Load auxiliary data for charge/multiplicity and axial ligand information."""
        try:
            # Try to load the processed_output.csv first as it has charge/multiplicity columns
            processed_path = "/home/pbuser/Desktop/PhD_WORK/heme/tables/processed_output.csv"
            auxiliary_data_sources = []
            
            if os.path.exists(processed_path):
                # Read only needed columns to avoid memory issues
                cols_to_read = ['file_name']
                
                # Check what columns are available
                with open(processed_path, 'r') as f:
                    header = f.readline().strip().split(',')
                    
                for col in header:
                    if col.lower() in ['charge', 'multiplicity'] and col not in cols_to_read:
                        cols_to_read.append(col)
                    if 'axial' in col.lower() and col not in cols_to_read:
                        cols_to_read.append(col)
                
                processed_data = pd.read_csv(processed_path, usecols=cols_to_read)
                auxiliary_data_sources.append(processed_data)
                print(f"Loaded processed_output.csv with columns: {list(processed_data.columns)} ({len(processed_data)} rows)")
            
            # Also try to load DB.csv for additional axial data
            db_path = "/home/pbuser/Desktop/PhD_WORK/heme/tables/DB.csv"
            if os.path.exists(db_path):
                try:
                    # For DB.csv, only get axial columns since it doesn't have proper charge/multiplicity
                    cols_to_read = ['file_name']
                    
                    with open(db_path, 'r') as f:
                        header = f.readline().strip().split(',')
                        
                    for col in header:
                        if 'axial' in col.lower() and col not in cols_to_read:
                            cols_to_read.append(col)
                    
                    if len(cols_to_read) > 1:  # Only load if we found axial columns
                        db_data = pd.read_csv(db_path, usecols=cols_to_read)
                        auxiliary_data_sources.append(db_data)
                        print(f"Loaded DB.csv with columns: {list(db_data.columns)} ({len(db_data)} rows)")
                except Exception as e:
                    print(f"Warning: Could not load DB.csv: {e}")
            
            # Try to load single_hemes.csv for additional axial data
            single_hemes_path = "/home/pbuser/Desktop/PhD_WORK/heme/tables/single_hemes.csv"
            if os.path.exists(single_hemes_path):
                try:
                    single_hemes = pd.read_csv(single_hemes_path)
                    # Map PDB ID to file_name format for merging
                    if '# PDB' in single_hemes.columns and 'axial1' in single_hemes.columns:
                        # Create multiple filename formats to match various naming conventions
                        single_hemes_mapped = []
                        for _, row in single_hemes.iterrows():
                            pdb_id = row['# PDB']
                            for suffix in ['01.log', '05.log', '12.log', '16.log', '05re.log', '12re.log']:
                                mapped_row = {
                                    'file_name': f"{pdb_id}{suffix}",
                                    'axial1': row['axial1'],
                                    'axial2': row['axial2']
                                }
                                single_hemes_mapped.append(mapped_row)
                        
                        single_hemes_expanded = pd.DataFrame(single_hemes_mapped)
                        auxiliary_data_sources.append(single_hemes_expanded)
                        print(f"Loaded single_hemes.csv expanded to {len(single_hemes_expanded)} filename mappings")
                except Exception as e:
                    print(f"Warning: Could not load single_hemes.csv: {e}")
            
            # Combine all auxiliary data sources to maximize coverage
            if auxiliary_data_sources:
                # Start with an empty base and concatenate all sources
                all_data = []
                
                for i, source in enumerate(auxiliary_data_sources):
                    source_copy = source.copy()
                    source_copy['source'] = i  # Track which source each row came from
                    all_data.append(source_copy)
                
                # Concatenate all sources
                combined_data = pd.concat(all_data, ignore_index=True)
                
                # Remove duplicates, keeping the first occurrence (which prioritizes processed_output.csv)
                # Sort by source to ensure processed_output (source 0) comes first
                combined_data = combined_data.sort_values('source')
                self.auxiliary_data = combined_data.drop_duplicates('file_name', keep='first').drop('source', axis=1)
                
                print(f"Final auxiliary data shape: {self.auxiliary_data.shape}")
                print(f"Final auxiliary data columns: {list(self.auxiliary_data.columns)}")
                
                # Report coverage statistics
                if 'charge' in self.auxiliary_data.columns:
                    charge_coverage = self.auxiliary_data['charge'].notna().sum()
                    print(f"Charge/multiplicity coverage: {charge_coverage}/{len(self.auxiliary_data)} files")
                
                if 'axial1' in self.auxiliary_data.columns:
                    axial_coverage = self.auxiliary_data['axial1'].notna().sum()
                    print(f"Axial ligand coverage: {axial_coverage}/{len(self.auxiliary_data)} files")
                    
            else:
                print("No auxiliary data files found - proceeding without auxiliary data")
                self.auxiliary_data = pd.DataFrame()
                
        except Exception as e:
            print(f"Error loading auxiliary data: {e}")
            self.auxiliary_data = pd.DataFrame()
            
    def identify_outliers(self, df, columns, method='iqr', multiplier=3):
        """Identify outliers using IQR or Z-score method."""
        outliers = {}
        
        for col in columns:
            if col not in df.columns:
                continue
                
            valid_data = df[col].dropna()
            if len(valid_data) == 0:
                continue
                
            if method == 'iqr':
                Q1 = valid_data.quantile(0.25)
                Q3 = valid_data.quantile(0.75)
                IQR = Q3 - Q1
                lower_bound = Q1 - multiplier * IQR
                upper_bound = Q3 + multiplier * IQR
                outlier_mask = (df[col] < lower_bound) | (df[col] > upper_bound)
            else:  # z-score
                mean = valid_data.mean()
                std = valid_data.std()
                z_scores = np.abs((df[col] - mean) / std)
                outlier_mask = z_scores > multiplier
            
            outlier_indices = df[outlier_mask].index
            if len(outlier_indices) > 0:
                outliers[col] = {
                    'indices': outlier_indices,
                    'values': df.loc[outlier_indices, col].tolist(),
                    'filenames': df.loc[outlier_indices, 'filename'].tolist() if 'filename' in df.columns else [],
                    'pdb_ids': df.loc[outlier_indices, 'pdb_id'].tolist() if 'pdb_id' in df.columns else []
                }
        
        return outliers
        
    def generate_outlier_report(self, table_name, outliers):
        """Generate a detailed outlier report."""
        report_file = self.output_dir / f"{table_name}_outlier_report.txt"
        
        with open(report_file, 'w') as f:
            f.write(f"Outlier Analysis Report for {table_name}\n")
            f.write("="*60 + "\n\n")
            
            if not outliers:
                f.write("No outliers detected.\n")
                return
            
            for col, data in outliers.items():
                f.write(f"Column: {col}\n")
                f.write(f"Number of outliers: {len(data['indices'])}\n")
                f.write(f"Outlier values: {data['values']}\n")
                if data['pdb_ids']:
                    f.write(f"PDB IDs: {data['pdb_ids']}\n")
                if data['filenames']:
                    f.write(f"Filenames: {data['filenames']}\n")
                f.write("\n" + "-"*40 + "\n\n")
        
        print(f"Outlier report saved: {report_file}")
        return outliers
        
    def remove_outliers_from_data(self, df, outliers):
        """Remove outliers from dataset and return cleaned data."""
        if not outliers:
            return df
            
        # Collect all outlier indices
        all_outlier_indices = set()
        for col_data in outliers.values():
            all_outlier_indices.update(col_data['indices'])
        
        # Remove outliers
        cleaned_df = df.drop(index=list(all_outlier_indices)).reset_index(drop=True)
        print(f"Removed {len(all_outlier_indices)} outlier samples from dataset")
        
        return cleaned_df
        
    def create_stacked_histogram(self, df, column, ax, color_by=None, show_charge_mult=True, show_axial=True, show_other=True):
        """Create a stacked histogram with charge-multiplicity and axial ligand breakdown."""
        if column not in df.columns:
            ax.text(0.5, 0.5, f'Column {column} not found', ha='center', va='center')
            return
            
        valid_data = df.dropna(subset=[column])
        if len(valid_data) == 0:
            ax.text(0.5, 0.5, 'No valid data', ha='center', va='center')
            return
            
        # Create bins
        bins = np.histogram_bin_edges(valid_data[column], bins=20)
        
        # Simple histogram if no auxiliary data
        if not (show_charge_mult or show_axial) or self.auxiliary_data.empty:
            counts, bin_edges = np.histogram(valid_data[column], bins=bins)
            ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
            ax.set_ylabel('Count')
            return
            
        # Merge with auxiliary data
        merged_df = self.merge_with_auxiliary(valid_data)
        
        # Check if we still have the target column after merging and have required grouping columns
        has_target_column = column in merged_df.columns
        has_charge_mult = 'charge_multiplicity' in merged_df.columns and merged_df['charge_multiplicity'].notna().sum() > 0
        has_axial = any(col.startswith('axial') for col in merged_df.columns)
        
        if not has_target_column:
            # If target column is lost during merge, fall back to simple histogram
            counts, bin_edges = np.histogram(valid_data[column], bins=bins)
            ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
            ax.set_ylabel('Count')
            return
        
        if show_axial and has_axial:
            # Group by axial ligand combinations
            axial_cols = [col for col in merged_df.columns if col.startswith('axial')]
            if axial_cols:
                # Create combined axial label with better handling
                def create_axial_combo(row):
                    axial_values = [str(row[col]) for col in axial_cols if pd.notna(row[col]) and row[col] != 'Unknown']
                    if len(axial_values) >= 2:
                        # Sort to ensure consistent ordering
                        sorted_axials = sorted(axial_values)
                        return '-'.join(sorted_axials)
                    return None
                
                merged_df['axial_combo'] = merged_df.apply(create_axial_combo, axis=1)
                
                # Define the main 5 axial combinations
                top_5_axial_combos = {'CYS-HOH', 'HIS-HIS', 'HIS-HOH', 'HIS-MET', 'HIS-OXY'}
                
                # Separate data into main 5 and others
                main_5_data = merged_df[merged_df['axial_combo'].isin(top_5_axial_combos)]
                other_data = merged_df[~merged_df['axial_combo'].isin(top_5_axial_combos) & merged_df['axial_combo'].notna()]
                
                # Debug: report what axial combinations we found
                unique_combos = merged_df['axial_combo'].dropna().unique()
                if len(unique_combos) > 0:
                    print(f"DEBUG: Found axial combinations: {list(unique_combos)}")
                    if len(other_data) > 0 and not show_other:
                        print(f"DEBUG: {len(other_data)} samples excluded due to non-main-5 axial combinations")
                
                if len(main_5_data) > 0:
                    # Plot main 5 combinations
                    groups = main_5_data.groupby('axial_combo')
                    sorted_groups = sorted(groups, key=lambda x: x[0])
                    unique_main_combos = [group[0] for group in sorted_groups]
                    color_map = get_axial_ligand_colors(unique_main_combos)
                    
                    bottom = np.zeros(len(bins)-1)
                    for group_name, group_data in sorted_groups:
                        if len(group_data) > 0 and column in group_data.columns:
                            counts, _ = np.histogram(group_data[column], bins=bins)
                            color = color_map.get(group_name, COLORBLIND_PALETTE[0])
                            ax.bar(bins[:-1], counts, width=np.diff(bins), bottom=bottom, 
                                  label=f'{group_name} (n={len(group_data)})', alpha=0.7, color=color, edgecolor='black')
                            bottom += counts
                    
                    # Add "Other" category if requested and there's data
                    if show_other and len(other_data) > 0 and column in other_data.columns:
                        other_counts, _ = np.histogram(other_data[column], bins=bins)
                        ax.bar(bins[:-1], other_counts, width=np.diff(bins), bottom=bottom, 
                              label=f'Other (n={len(other_data)})', alpha=0.5, color='lightgray', edgecolor='black')
                        bottom += other_counts
                else:
                    # Fallback if no top 5 combinations found
                    if column in merged_df.columns:
                        counts, bin_edges = np.histogram(merged_df[column], bins=bins)
                        ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
                    else:
                        counts, bin_edges = np.histogram(valid_data[column], bins=bins)
                        ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
            else:
                # Fallback to simple histogram
                counts, bin_edges = np.histogram(valid_data[column], bins=bins)
                ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
                
        elif show_charge_mult and has_charge_mult:
            # Group by charge-multiplicity combinations (only if axial failed)
            groups = merged_df.groupby('charge_multiplicity')
            unique_combos = list(groups.groups.keys())
            # Limit to reasonable number of combinations to avoid hundreds of groups
            if len(unique_combos) > 10:
                # Only show the 10 most common combinations
                combo_counts = merged_df['charge_multiplicity'].value_counts()
                top_combos = combo_counts.head(10).index.tolist()
                filtered_df = merged_df[merged_df['charge_multiplicity'].isin(top_combos)]
                groups = filtered_df.groupby('charge_multiplicity')
                unique_combos = top_combos
            
            color_map = get_charge_multiplicity_colors(unique_combos)
            
            bottom = np.zeros(len(bins)-1)
            for group_name, group_data in groups:
                if len(group_data) > 0 and column in group_data.columns:
                    counts, _ = np.histogram(group_data[column], bins=bins)
                    color = color_map.get(group_name, COLORBLIND_PALETTE[0])
                    ax.bar(bins[:-1], counts, width=np.diff(bins), bottom=bottom, 
                          label=f'q={group_name}', alpha=0.7, color=color, edgecolor='black')
                    bottom += counts
        else:
            # Fallback to simple histogram when no grouping data is available
            counts, bin_edges = np.histogram(valid_data[column], bins=bins)
            ax.bar(bin_edges[:-1], counts, width=np.diff(bin_edges), alpha=0.7, edgecolor='black')
            
        ax.set_ylabel('Count')
        if show_charge_mult or show_axial:
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
            
    def merge_with_auxiliary(self, df):
        """Merge dataframe with auxiliary charge/multiplicity/axial data."""
        if self.auxiliary_data.empty or 'filename' not in df.columns:
            return df
            
        # Create mapping between filenames
        df_copy = df.copy()
        df_copy['base_filename'] = df_copy['filename'].str.replace('.json', '.log')
        
        # Merge based on filename
        merged = df_copy.merge(self.auxiliary_data, left_on='base_filename', right_on='file_name', how='left')
        
        # Create charge-multiplicity combination if both exist
        charge_cols = [col for col in merged.columns if 'charge' in col.lower()]
        mult_cols = [col for col in merged.columns if 'multiplicity' in col.lower()]
        
        if charge_cols and mult_cols:
            charge_col = charge_cols[0]
            mult_col = mult_cols[0]
            # Only create charge_multiplicity for rows where both values are not null
            merged['charge_multiplicity'] = merged.apply(
                lambda row: f"{row[charge_col]},{row[mult_col]}" 
                if pd.notna(row[charge_col]) and pd.notna(row[mult_col]) 
                else None, axis=1
            )
            
        return merged
    
    def color_scatter_by_axial(self, ax, df, x_col, y_col, show_other=True):
        """Color scatter plot points by axial ligand combinations.
        
        Parameters:
        -----------
        ax : matplotlib.axes.Axes
            The axes to plot on
        df : pandas.DataFrame
            The dataframe containing the data
        x_col : str
            Column name for x-axis
        y_col : str
            Column name for y-axis
        show_other : bool, default=True
            Whether to show samples not in the main 5 axial combinations as "Other"
        """
        # Merge with auxiliary data to get axial ligand info
        merged_df = self.merge_with_auxiliary(df)
        
        # Check if we have axial data
        axial_cols = [col for col in merged_df.columns if col.startswith('axial')]
        if not axial_cols:
            # Fallback to simple scatter
            ax.scatter(df[x_col], df[y_col], alpha=0.6, s=50, color='gray')
            return
        
        # Create axial combinations with better handling
        def create_axial_combo(row):
            axial_values = [str(row[col]) for col in axial_cols if pd.notna(row[col]) and row[col] != 'Unknown']
            if len(axial_values) >= 2:
                # Sort to ensure consistent ordering (e.g., CYS-HOH not HOH-CYS)
                sorted_axials = sorted(axial_values)
                return '-'.join(sorted_axials)
            return None
        
        merged_df['axial_combo'] = merged_df.apply(create_axial_combo, axis=1)
        
        # Define the main 5 axial combinations
        top_5_axial_combos = {'CYS-HOH', 'HIS-HIS', 'HIS-HOH', 'HIS-MET', 'HIS-OXY'}
        
        # Separate data into main 5 and others
        main_5_data = merged_df[merged_df['axial_combo'].isin(top_5_axial_combos)]
        other_data = merged_df[~merged_df['axial_combo'].isin(top_5_axial_combos) & merged_df['axial_combo'].notna()]
        
        # Plot each of the main 5 axial combinations with consistent colors
        plotted_any = False
        for combo in top_5_axial_combos:
            combo_data = main_5_data[main_5_data['axial_combo'] == combo]
            if len(combo_data) > 0 and x_col in combo_data.columns and y_col in combo_data.columns:
                color = self.axial_color_map.get(combo, COLORBLIND_PALETTE[0])
                ax.scatter(combo_data[x_col], combo_data[y_col], 
                          color=color, label=f'{combo} (n={len(combo_data)})', alpha=0.7, s=50)
                plotted_any = True
        
        # Plot "Other" category if requested and there's data
        if show_other and len(other_data) > 0 and x_col in other_data.columns and y_col in other_data.columns:
            ax.scatter(other_data[x_col], other_data[y_col], 
                      color='lightgray', label=f'Other (n={len(other_data)})', alpha=0.5, s=30)
            plotted_any = True
        
        if plotted_any:
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        elif len(merged_df) > 0:
            # If no valid axial data found, debug what we have
            print(f"DEBUG: No valid axial combinations found. Available combinations: {merged_df['axial_combo'].unique()}")
            ax.scatter(df[x_col], df[y_col], alpha=0.6, s=50, color='gray')
        
        # Report statistics
        if not show_other and len(other_data) > 0:
            print(f"INFO: {len(other_data)} samples excluded from scatter plot (not in main 5 axial combinations)")
        elif show_other and len(other_data) > 0:
            other_combos = other_data['axial_combo'].unique()
            print(f"INFO: {len(other_data)} samples in 'Other' category with combinations: {list(other_combos)}")
                
    def plot_fe_coordination_analysis(self, show_charge_mult=False, show_axial=True, show_other=True):
        """Create exploratory plots for Fe coordination analysis."""
        if 'fe_coordination_analysis' not in self.tables:
            print("Fe coordination analysis table not found")
            return
            
        df = self.tables['fe_coordination_analysis']
        
        # Identify and remove outliers
        outlier_columns = ['coordination_number', 'heme_nitrogen_bonds', 'axial_bonds', 'd_electron_count']
        outliers = self.identify_outliers(df, outlier_columns, method='iqr', multiplier=3)
        self.generate_outlier_report('fe_coordination_analysis', outliers)
        df_clean = self.remove_outliers_from_data(df, outliers)
        
        # Create both versions of the plot
        for include_other in [True, False]:
            suffix = "all_samples" if include_other else "main5_only"
            
            # Create subplot grid (removed oxidation state plot)
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            
            # 1. Coordination number distribution
            self.create_stacked_histogram(df_clean, 'coordination_number', axes[0,0], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[0,0].set_xlabel('Coordination Number')
            
            # 2. Heme nitrogen bonds vs axial bonds (colored by axial ligands)
            valid_bonds = df_clean.dropna(subset=['heme_nitrogen_bonds', 'axial_bonds'])
            if len(valid_bonds) > 0:
                self.color_scatter_by_axial(axes[0,1], valid_bonds, 'heme_nitrogen_bonds', 'axial_bonds', show_other=include_other)
                axes[0,1].set_xlabel('Heme Nitrogen Bonds')
                axes[0,1].set_ylabel('Axial Bonds')
            else:
                axes[0,1].text(0.5, 0.5, 'No valid data', ha='center', va='center')
            
            # 3. d-electron count distribution
            self.create_stacked_histogram(df_clean, 'd_electron_count', axes[1,0], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[1,0].set_xlabel('d-Electron Count')
            
            # 4. Spin state distribution
            spin_state_counts = df_clean['nao_spin_state'].value_counts()
            if not spin_state_counts.empty:
                axes[1,1].pie(spin_state_counts.values, labels=spin_state_counts.index, autopct='%1.1f%%')
            else:
                axes[1,1].text(0.5, 0.5, 'No spin state data', ha='center', va='center')
            
            plt.tight_layout()
            plt.savefig(self.output_dir / f'fe_coordination_exploratory_{suffix}.png', dpi=300, bbox_inches='tight')
            plt.close()
            
        print("Fe coordination exploratory plots saved (both versions)")
        
    def plot_orbital_analysis(self, show_charge_mult=False, show_axial=True, show_other=True):
        """Create exploratory plots for orbital analysis."""
        if 'orbital_analysis' not in self.tables:
            print("Orbital analysis table not found")
            return
            
        df = self.tables['orbital_analysis']
        
        # Create both versions of the plot
        for include_other in [True, False]:
            suffix = "all_samples" if include_other else "main5_only"
            
            # Create subplot grid (removed top right plot)
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            
            # 1. HOMO-LUMO gap distribution (eV)
            self.create_stacked_histogram(df, 'alpha_gap_ev', axes[0,0], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[0,0].set_xlabel('Gap (eV)')
            
            # 2. Alpha vs Beta gap comparison (colored by axial ligands)
            unrestricted = df[df['is_unrestricted'] == True].dropna(subset=['alpha_gap_ev', 'beta_gap_ev'])
            if len(unrestricted) > 0:
                self.color_scatter_by_axial(axes[0,1], unrestricted, 'alpha_gap_ev', 'beta_gap_ev', show_other=include_other)
                axes[0,1].plot([0, 4], [0, 4], 'r--', alpha=0.5)  # diagonal line
                axes[0,1].set_xlabel('Alpha Gap (eV)')
                axes[0,1].set_ylabel('Beta Gap (eV)')
            else:
                axes[0,1].text(0.5, 0.5, 'No unrestricted calculations', ha='center', va='center')
            
            # 3. Restricted vs Unrestricted calculation frequency
            calc_type_counts = df['is_unrestricted'].value_counts()
            labels = ['Restricted' if not x else 'Unrestricted' for x in calc_type_counts.index]
            axes[1,0].pie(calc_type_counts.values, labels=labels, autopct='%1.1f%%')
            
            # 4. HOMO level distribution
            self.create_stacked_histogram(df, 'alpha_homo', axes[1,1], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[1,1].set_xlabel('HOMO Energy (au)')
            
            plt.tight_layout()
            plt.savefig(self.output_dir / f'orbital_analysis_exploratory_{suffix}.png', dpi=300, bbox_inches='tight')
            plt.close()
            
        print("Orbital analysis exploratory plots saved (both versions)")
        
    def plot_charge_transfer_analysis(self, show_charge_mult=False, show_axial=True, show_other=True):
        """Create exploratory plots for charge transfer analysis."""
        if 'charge_transfer_analysis' not in self.tables:
            print("Charge transfer analysis table not found")
            return
            
        df = self.tables['charge_transfer_analysis']
        
        # Identify and remove outliers
        outlier_columns = ['ligand_to_fe_donation_energy', 'fe_to_ligand_backbonding_energy', 
                          'net_charge_transfer', 'total_interactions', 'fe_donor_count']
        outliers = self.identify_outliers(df, outlier_columns, method='iqr', multiplier=3)
        self.generate_outlier_report('charge_transfer_analysis', outliers)
        df_clean = self.remove_outliers_from_data(df, outliers)
        
        # Create both versions of the plot
        for include_other in [True, False]:
            suffix = "all_samples" if include_other else "main5_only"
            
            # Create subplot grid
            fig, axes = plt.subplots(2, 3, figsize=(18, 12))
            
            # 1. Donation vs Backbonding energy (colored by axial ligands)
            valid_transfer = df_clean.dropna(subset=['ligand_to_fe_donation_energy', 'fe_to_ligand_backbonding_energy'])
            if len(valid_transfer) > 0:
                self.color_scatter_by_axial(axes[0,0], valid_transfer, 'ligand_to_fe_donation_energy', 'fe_to_ligand_backbonding_energy', show_other=include_other)
                axes[0,0].set_xlabel('Ligand→Fe Donation (kcal/mol)')
                axes[0,0].set_ylabel('Fe→Ligand Backbonding (kcal/mol)')
            else:
                axes[0,0].text(0.5, 0.5, 'No valid data', ha='center', va='center')
            
            # 2. Net charge transfer distribution
            self.create_stacked_histogram(df_clean, 'net_charge_transfer', axes[0,1], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[0,1].set_xlabel('Net Charge Transfer (kcal/mol)')
            axes[0,1].axvline(x=0, color='red', linestyle='--', alpha=0.7)
            
            # 3. Total interactions vs average energy (colored by axial ligands)
            valid_int = df_clean.dropna(subset=['total_interactions', 'average_interaction_energy'])
            if len(valid_int) > 0:
                self.color_scatter_by_axial(axes[0,2], valid_int, 'total_interactions', 'average_interaction_energy', show_other=include_other)
                axes[0,2].set_xlabel('Total Interactions')
                axes[0,2].set_ylabel('Average Energy (kcal/mol)')
            else:
                axes[0,2].text(0.5, 0.5, 'No valid data', ha='center', va='center')
            
            # 4. Fe donor vs acceptor count (colored by axial ligands)
            valid_fe = df_clean.dropna(subset=['fe_donor_count', 'fe_acceptor_count'])
            if len(valid_fe) > 0:
                self.color_scatter_by_axial(axes[1,0], valid_fe, 'fe_donor_count', 'fe_acceptor_count', show_other=include_other)
                axes[1,0].set_xlabel('Fe Donor Count')
                axes[1,0].set_ylabel('Fe Acceptor Count')
            else:
                axes[1,0].text(0.5, 0.5, 'No valid data', ha='center', va='center')
            
            # 5. Donation energy distribution
            self.create_stacked_histogram(df_clean, 'ligand_to_fe_donation_energy', axes[1,1], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[1,1].set_xlabel('Ligand→Fe Donation (kcal/mol)')
            
            # 6. Backbonding energy distribution
            self.create_stacked_histogram(df_clean, 'fe_to_ligand_backbonding_energy', axes[1,2], 
                                        show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
            axes[1,2].set_xlabel('Fe→Ligand Backbonding (kcal/mol)')
            
            plt.tight_layout()
            plt.savefig(self.output_dir / f'charge_transfer_exploratory_{suffix}.png', dpi=300, bbox_inches='tight')
            plt.close()
            
        print("Charge transfer exploratory plots saved (both versions)")
        
    def plot_spin_contamination_analysis(self, show_charge_mult=False, show_axial=True, show_other=True):
        """Create exploratory plots for spin contamination analysis."""
        if 'spin_contamination_analysis' not in self.tables:
            print("Spin contamination analysis table not found")
            return
            
        df = self.tables['spin_contamination_analysis']
        
        # Identify and remove outliers for annihilation effectiveness
        outlier_columns = ['annihilation_effectiveness']
        outliers = self.identify_outliers(df, outlier_columns, method='iqr', multiplier=3)
        self.generate_outlier_report('spin_contamination_analysis', outliers)
        df_clean = self.remove_outliers_from_data(df, outliers)
        
        # Create both versions of the plot
        for include_other in [True, False]:
            suffix = "all_samples" if include_other else "main5_only"
            
            # Create subplot grid
            fig, axes = plt.subplots(2, 3, figsize=(18, 12))
            
            # 1. Multiplicity distribution - check if column exists first
            if 'multiplicity' in df_clean.columns:
                self.create_stacked_histogram(df_clean, 'multiplicity', axes[0,0], 
                                            show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
                axes[0,0].set_xlabel('Multiplicity')
            else:
                axes[0,0].text(0.5, 0.5, 'Multiplicity column not found', ha='center', va='center')
                axes[0,0].set_xlabel('Multiplicity (Not Available)')
            
            # 2. Percent contamination distribution
            if 'percent_contamination' in df_clean.columns:
                self.create_stacked_histogram(df_clean, 'percent_contamination', axes[0,1], 
                                            show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
                axes[0,1].set_xlabel('Percent Contamination (%)')
                axes[0,1].axvline(x=10, color='red', linestyle='--', alpha=0.7, label='10% threshold')
                axes[0,1].legend()
            else:
                axes[0,1].text(0.5, 0.5, 'Percent contamination column not found', ha='center', va='center')
                axes[0,1].set_xlabel('Percent Contamination (Not Available)')
            
            # 3. Contamination severity distribution (sorted by severity)
            if 'contamination_severity' in df_clean.columns:
                severity_counts = df_clean['contamination_severity'].value_counts()
            else:
                severity_counts = pd.Series(dtype=object)
            if not severity_counts.empty:
                # Sort by severity level
                severity_order = ['negligible', 'minor', 'moderate', 'severe', 'significant']
                sorted_counts = []
                sorted_labels = []
                for severity in severity_order:
                    if severity in severity_counts.index:
                        sorted_counts.append(severity_counts[severity])
                        sorted_labels.append(severity)
                
                axes[0,2].pie(sorted_counts, labels=sorted_labels, autopct='%1.1f%%')
            else:
                axes[0,2].text(0.5, 0.5, 'No severity data', ha='center', va='center')
            
            # 4. Theoretical vs Final S² (colored by axial ligands)
            s2_cols = ['theoretical_s_squared', 'final_s_squared']
            if all(col in df_clean.columns for col in s2_cols):
                valid_s2 = df_clean.dropna(subset=s2_cols)
                if len(valid_s2) > 0:
                    self.color_scatter_by_axial(axes[1,0], valid_s2, 'theoretical_s_squared', 'final_s_squared', show_other=include_other)
                    max_s2 = max(valid_s2['theoretical_s_squared'].max(), valid_s2['final_s_squared'].max())
                    axes[1,0].plot([0, max_s2], [0, max_s2], 'r--', alpha=0.5)
                    axes[1,0].set_xlabel('Theoretical S²')
                    axes[1,0].set_ylabel('Final S²')
                else:
                    axes[1,0].text(0.5, 0.5, 'No S² data', ha='center', va='center')
            else:
                axes[1,0].text(0.5, 0.5, 'S² columns not found', ha='center', va='center')
                axes[1,0].set_xlabel('Theoretical S² (Not Available)')
                axes[1,0].set_ylabel('Final S² (Not Available)')
            
            # 5. Annihilation effectiveness distribution
            if 'annihilation_effectiveness' in df_clean.columns:
                self.create_stacked_histogram(df_clean, 'annihilation_effectiveness', axes[1,1], 
                                            show_charge_mult=show_charge_mult, show_axial=show_axial, show_other=include_other)
                axes[1,1].set_xlabel('Annihilation Effectiveness (%)')
            else:
                axes[1,1].text(0.5, 0.5, 'Annihilation effectiveness column not found', ha='center', va='center')
                axes[1,1].set_xlabel('Annihilation Effectiveness (Not Available)')
            
            # 6. Valid spin state distribution
            if 'is_valid_spin_state' in df_clean.columns:
                valid_spin_counts = df_clean['is_valid_spin_state'].value_counts()
                if not valid_spin_counts.empty:
                    labels = ['Invalid' if not x else 'Valid' for x in valid_spin_counts.index]
                    axes[1,2].pie(valid_spin_counts.values, labels=labels, autopct='%1.1f%%')
                else:
                    axes[1,2].text(0.5, 0.5, 'No valid spin state data', ha='center', va='center')
            else:
                axes[1,2].text(0.5, 0.5, 'Valid spin state column not found', ha='center', va='center')
            
            plt.tight_layout()
            plt.savefig(self.output_dir / f'spin_contamination_exploratory_{suffix}.png', dpi=300, bbox_inches='tight')
            plt.close()
            
        print("Spin contamination exploratory plots saved (both versions)")
        
    def plot_correlation_matrix(self):
        """Create correlation matrices for numerical data across all tables."""
        fig, axes = plt.subplots(2, 2, figsize=(20, 16))
        
        table_names = ['fe_coordination_analysis', 'orbital_analysis', 'charge_transfer_analysis', 'spin_contamination_analysis']
        
        for i, table_name in enumerate(table_names):
            if table_name in self.tables:
                df = self.tables[table_name]
                # Select only numerical columns
                numerical_cols = df.select_dtypes(include=[np.number]).columns
                if len(numerical_cols) > 1:
                    corr_matrix = df[numerical_cols].corr()
                    
                    row, col = i // 2, i % 2
                    im = axes[row, col].imshow(corr_matrix.values, cmap='RdBu_r', vmin=-1, vmax=1)
                    
                    # Add correlation values as text
                    for j in range(len(corr_matrix.columns)):
                        for k in range(len(corr_matrix.columns)):
                            text = axes[row, col].text(k, j, f'{corr_matrix.iloc[j, k]:.2f}',
                                                     ha="center", va="center", color="black", fontsize=8)
                    
                    axes[row, col].set_xticks(range(len(corr_matrix.columns)))
                    axes[row, col].set_yticks(range(len(corr_matrix.columns)))
                    axes[row, col].set_xticklabels(corr_matrix.columns, rotation=45, ha='right')
                    axes[row, col].set_yticklabels(corr_matrix.columns)
                    
                    # Add colorbar
                    cbar = plt.colorbar(im, ax=axes[row, col])
                    cbar.set_label('Correlation', rotation=270, labelpad=15)
                else:
                    row, col = i // 2, i % 2
                    axes[row, col].text(0.5, 0.5, f'Insufficient numerical data\n{table_name}', 
                                      ha='center', va='center')
            else:
                row, col = i // 2, i % 2
                axes[row, col].text(0.5, 0.5, f'Table not found\n{table_name}', ha='center', va='center')
        
        plt.tight_layout()
        plt.savefig(self.output_dir / 'correlation_matrices.png', dpi=300, bbox_inches='tight')
        plt.close()
        print("Correlation matrices saved")
        
    def generate_summary_report(self):
        """Generate a summary report of all loaded tables."""
        summary_file = self.output_dir / 'data_summary.txt'
        
        with open(summary_file, 'w') as f:
            f.write("Quantum Chemistry Analysis Tables Summary\n")
            f.write("="*50 + "\n\n")
            
            for table_name, df in self.tables.items():
                f.write(f"Table: {table_name}\n")
                f.write(f"Rows: {len(df)}\n")
                f.write(f"Columns: {len(df.columns)}\n")
                f.write(f"Numerical columns: {len(df.select_dtypes(include=[np.number]).columns)}\n")
                f.write(f"Non-null percentage: {(df.notna().sum().sum() / (len(df) * len(df.columns)) * 100):.1f}%\n")
                f.write("\nColumn summary:\n")
                
                for col in df.columns:
                    non_null_count = df[col].notna().sum()
                    f.write(f"  {col}: {non_null_count}/{len(df)} non-null ({non_null_count/len(df)*100:.1f}%)\n")
                
                f.write("\n" + "-"*40 + "\n\n")
        
        print(f"Summary report saved to {summary_file}")
        
    def plot_all(self, show_charge_mult=False, show_axial=True, show_other=True):
        """Generate all exploratory plots with both versions (all samples and main 5 only)."""
        print("Generating exploratory plots for quantum chemistry analysis tables...")
        print("Creating both versions: all samples and main 5 axial combinations only")
        print(f"Output directory: {self.output_dir}")
        
        self.plot_fe_coordination_analysis(show_charge_mult, show_axial, show_other)
        self.plot_orbital_analysis(show_charge_mult, show_axial, show_other)
        self.plot_charge_transfer_analysis(show_charge_mult, show_axial, show_other)
        self.plot_spin_contamination_analysis(show_charge_mult, show_axial, show_other)
        self.plot_correlation_matrix()
        self.generate_summary_report()
        
        print(f"\nAll exploratory plots completed! Check {self.output_dir} for results.")
        print("Files generated:")
        print("  - *_all_samples.png (includes all data points)")
        print("  - *_main5_only.png (only top 5 axial ligand combinations)")
    
    def plot_all_main5_only(self):
        """Generate plots showing only the main 5 axial ligand combinations."""
        print("Note: plot_all() now generates both versions automatically.")
        print("Generating plots with both all samples and main 5 only...")
        self.plot_all(show_charge_mult=False, show_axial=True, show_other=True)
    
    def plot_all_with_other(self):
        """Generate plots showing main 5 axial ligand combinations plus 'Other' category."""
        print("Note: plot_all() now generates both versions automatically.")
        print("Generating plots with both all samples and main 5 only...")
        self.plot_all(show_charge_mult=False, show_axial=True, show_other=True)
        
        # Print summary of outlier reports
        outlier_files = list(self.output_dir.glob("*_outlier_report.txt"))
        if outlier_files:
            print(f"\nOutlier reports generated: {len(outlier_files)} files")
            for report_file in outlier_files:
                print(f"  - {report_file.name}")


def main():
    """Main function to run all exploratory plotting."""
    plotter = QMAnalysisPlotter()
    plotter.plot_all(show_charge_mult=True, show_axial=True)


if __name__ == "__main__":
    main()
